spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: none
      database-platform: org.hibernate.dialect.MariaDBDialect
logging:
   level:
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql.BasicBinder: WARN
