logging:
  level:
    eu.clarin.cmdi.vlo.batchimporter: INFO
vlo:
  importer:
    api-base-url: http://localhost:8708
    metadata-source:
#      roots: 
#        - name: 'First set'
#          path: /my/vlo/records/first
#        - name: 'Second set'
#          path: /my/vlo/records/second
