//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.13 at 10:31:52 AM CEST 
//
package eu.clarin.cmdi.vlo.facets;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{}concept"/&gt;
 *           &lt;element ref="{}pattern"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{}blacklistPattern" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="allowMultipleValues" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="definition" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="isCaseInsensitive" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conceptOrPattern",
    "blacklistPattern"
})
@XmlRootElement(name = "facetConcept")
public class FacetConcept {

    @XmlElementRefs({
        @XmlElementRef(name = "pattern", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "concept", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> conceptOrPattern;
    protected List<String> blacklistPattern;
    @XmlAttribute(name = "allowMultipleValues")
    protected Boolean allowMultipleValues;
    @XmlAttribute(name = "definition")
    @XmlSchemaType(name = "anySimpleType")
    protected String definition;
    @XmlAttribute(name = "description")
    @XmlSchemaType(name = "anySimpleType")
    protected String description;
    @XmlAttribute(name = "isCaseInsensitive")
    protected Boolean isCaseInsensitive;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;

    /**
     * Gets the value of the conceptOrPattern property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the conceptOrPattern property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConceptOrPattern().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list      {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     *
     */
    public List<JAXBElement<String>> getConceptOrPattern() {
        if (conceptOrPattern == null) {
            conceptOrPattern = new ArrayList<JAXBElement<String>>();
        }
        return this.conceptOrPattern;
    }

    /**
     * Gets the value of the blacklistPattern property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the blacklistPattern property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlacklistPattern().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     *
     *
     */
    public List<String> getBlacklistPattern() {
        if (blacklistPattern == null) {
            blacklistPattern = new ArrayList<String>();
        }
        return this.blacklistPattern;
    }

    /**
     * Gets the value of the allowMultipleValues property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isAllowMultipleValues() {
        return allowMultipleValues;
    }

    /**
     * Sets the value of the allowMultipleValues property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setAllowMultipleValues(Boolean value) {
        this.allowMultipleValues = value;
    }

    /**
     * Gets the value of the definition property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the isCaseInsensitive property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isIsCaseInsensitive() {
        return isCaseInsensitive;
    }

    /**
     * Sets the value of the isCaseInsensitive property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setIsCaseInsensitive(Boolean value) {
        this.isCaseInsensitive = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
