//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.13 at 10:31:52 AM CEST 
//
package eu.clarin.cmdi.vlo.facets;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 An FacetConceptsObjectFactory allows you to programatically construct new instances
 of the Java representation for XML content. The Java representation of XML
 content can consist of schema derived interfaces and classes representing the
 binding of schema type definitions, element declarations and model groups.
 Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class FacetConceptsObjectFactory {

    private final static QName _Concept_QNAME = new QName("", "concept");
    private final static QName _Pattern_QNAME = new QName("", "pattern");
    private final static QName _BlacklistPattern_QNAME = new QName("", "blacklistPattern");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: generated
     *
     */
    public FacetConceptsObjectFactory() {
    }

    /**
     * Create an instance of {@link FacetConcept }
     *
     */
    public FacetConcept createFacetConcept() {
        return new FacetConcept();
    }

    /**
     * Create an instance of {@link FacetConcepts }
     *
     */
    public FacetConcepts createFacetConcepts() {
        return new FacetConcepts();
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "concept")
    public JAXBElement<String> createConcept(String value) {
        return new JAXBElement<String>(_Concept_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "pattern")
    public JAXBElement<String> createPattern(String value) {
        return new JAXBElement<String>(_Pattern_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "blacklistPattern")
    public JAXBElement<String> createBlacklistPattern(String value) {
        return new JAXBElement<String>(_BlacklistPattern_QNAME, String.class, null, value);
    }

}
