spring:
  codec:
    max-in-memory-size: 50MB
  profiles:
    active: legacy
server:
  port: 8708
vlo:
  api:
    mapping:
      scheduler:
#        parallel:
#          threads: 10
        bounded-elastic:
          schedulerName: MappingRequestProcessorScheduler
          schedulerThreadCap: 8
          schedulerQueuedTaskCap: 100
          schedulerttlSeconds: 60
