spring:
  profiles:
    active: "solr"

api:
  facets:
    defaultFacetValueCountLimit: 10

solr:
  facets:
    defaultFields:
      - languageCode
      - collection
      - resourceClass
      - modality
      - format
      - keywords
      - genre
      - subject
      - country
      - organisation
  record:
    minimalFields: 
      - name
      - description
      - languageCode
      - license
      - licenseType
      - availability
      - _selfLink
      - id
      - resourceClass
      - _resourceRefCount
      - _fileName
    extraFields:
      - creator
      - collection
      - _languageCount
      - multilingual
      - modality
      - continent
      - country
      - genre
      - subject
      - organisation
      - accessInfo
      - keywords
      - nationalProject
      - _resourceRef
