name: CI

on:
  push:
    branches: ['**']
    tags: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create the release on a tag build
    env:
      MAVEN_OPTS: -Xmx2g
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn versions:set -DnewVersion=${{ github.ref_name }} versions:commit

      - name: Build
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Test
        run: mvn test -B

      - name: Package distribution
        run: mvn clean install -DskipTests=true -Pdocker

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          files: vlo-distribution/target/vlo-${{ github.ref_name }}-docker.tar.gz
